# Сингулярное разложение матриц.

### Задание №1.
Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

__Решение:__


In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

A = np.array([[1, 2, 0], [0 ,0 ,5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

U, s, W = np.linalg.svd(A)

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [2]:
print(A, '=', U, '*', D, '*', W, sep='\n')

[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
=
[[ 0.171  0.157 -0.531 -0.799 -0.162]
 [ 0.393 -0.529  0.613 -0.434  0.031]
 [-0.144 -0.824 -0.524  0.14   0.074]
 [ 0.888  0.061 -0.247  0.378 -0.06 ]
 [ 0.081  0.108 -0.082 -0.105  0.982]]
*
[[8.825 0.    0.   ]
 [0.    6.141 0.   ]
 [0.    0.    2.533]
 [0.    0.    0.   ]
 [0.    0.    0.   ]]
*
[[ 0.071  0.717  0.693]
 [-0.367  0.665 -0.65 ]
 [-0.927 -0.208  0.311]]


Проверим:

In [3]:
U @ D @ W

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1.,  0.]])

In [6]:
U @ U.T

array([[ 1.,  0., -0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [-0.,  0.,  1., -0.,  0.],
       [ 0.,  0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [5]:
W @ W.T

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

___
### Задание №2.
Для матрицы из предыдущего задания найти:

а) евклидову норму;
    
б) норму Фробениуса.

__Решение:__

а) Евклидова норма:

$$\left \| A \right \|_{E}=\mu_{max}.$$

In [7]:
max(s)

8.824868854820442

б) Норма Фробениуса:

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [8]:
np.linalg.norm(s)

11.045361017187261